### ISSUE TITLE
Update CodeMirror Julia support

### ISSUE THREAD

**Issue by savq** [fonsp/Pluto.jl#2943]
These are the pending tasks to update the CodeMiror Julia thingies:

### Dependencies

Merge PRs and release new versions.

- [x] JuliaPluto/lezer-julia#7
- [x] JuliaPluto/lang-julia#3
- [ ] JuliaPluto/codemirror-pluto-setup#15

JuliaPluto/codemirror-pluto-setup#15 can be merged together with this PR! For now, we can use its latest commit sha to test Pluto with the new versions

### Here

Refactor `frontend/components/CellInput/` modules that depend on lezer stuff.

- [ ] `block_matcher_plugin.js`
  - Works surprisingly well...
- [ ] `pkg_bubble_plugin.js`
  - This can probably be simplified with `ImportPath`
- [ ] `debug_syntax_plugin.js`
- [ ] `scopestate_statefield.js`
- [ ] `lezer_template.js`
- [ ] `mixedParsers.js`
- [ ] new color theme
